// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BiCircleFill: typeof import('~icons/bi/circle-fill')['default']
    BiEnvelopeFill: typeof import('~icons/bi/envelope-fill')['default']
    BiGithub: typeof import('~icons/bi/github')['default']
    BiGlobe2: typeof import('~icons/bi/globe2')['default']
    BiLinkedin: typeof import('~icons/bi/linkedin')['default']
    BiMoonFill: typeof import('~icons/bi/moon-fill')['default']
    BiPrinterFill: typeof import('~icons/bi/printer-fill')['default']
    BiSunFill: typeof import('~icons/bi/sun-fill')['default']
    BiTelephoneFill: typeof import('~icons/bi/telephone-fill')['default']
    Button: typeof import('C:/Development/Projects/Web/mackcutler-resume/src/components/Button.vue')['default']
    CarbonCircleSolid: typeof import('~icons/carbon/circle-solid')['default']
    Certifications: typeof import('C:/Development/Projects/Web/mackcutler-resume/src/components/Certifications.vue')['default']
    Contacts: typeof import('C:/Development/Projects/Web/mackcutler-resume/src/components/Contacts.vue')['default']
    Education: typeof import('C:/Development/Projects/Web/mackcutler-resume/src/components/Education.vue')['default']
    Experience: typeof import('C:/Development/Projects/Web/mackcutler-resume/src/components/Experience.vue')['default']
    Header: typeof import('C:/Development/Projects/Web/mackcutler-resume/src/components/Header.vue')['default']
    Headline: typeof import('C:/Development/Projects/Web/mackcutler-resume/src/components/Headline.vue')['default']
    LanguageSwitcher: typeof import('C:/Development/Projects/Web/mackcutler-resume/src/components/LanguageSwitcher.vue')['default']
    Paragraph: typeof import('C:/Development/Projects/Web/mackcutler-resume/src/components/Paragraph.vue')['default']
    Profile: typeof import('C:/Development/Projects/Web/mackcutler-resume/src/components/Profile.vue')['default']
    Projects: typeof import('C:/Development/Projects/Web/mackcutler-resume/src/components/Projects.vue')['default']
    Resume: typeof import('C:/Development/Projects/Web/mackcutler-resume/src/components/Resume.vue')['default']
    SimpleIconsNpm: typeof import('~icons/simple-icons/npm')['default']
    Skills: typeof import('C:/Development/Projects/Web/mackcutler-resume/src/components/Skills.vue')['default']
    SubTitle: typeof import('C:/Development/Projects/Web/mackcutler-resume/src/components/SubTitle.vue')['default']
    Title: typeof import('C:/Development/Projects/Web/mackcutler-resume/src/components/Title.vue')['default']
  }
}

export { }
